version: '3.8'

services:
  app:
    build:
      context: .
    container_name: laravel_app
    ports:
      - "9000:9000"
    volumes:
      - ./backend-laravel:/var/www
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: laravel_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:

