# fly.toml app configuration file generated for turturis-wave-wild-resonance-2978 on 2025-04-17T18:04:32-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'turturis-wave-wild-resonance-2978'
primary_region = 'sea'

[services]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
